current:
  year: 2025
ms:
  version: 1.0.0

server:
  port: 8085  
  forward-headers-strategy: framework

eureka:
  client:
    service-url.defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
  instance:
    prefer-ip-address: true

spring:
  application:
    name: ms-notification
  kafka: 
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
  datasource:
    url: jdbc:h2:mem:notificationdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
security:
  jwt:
    secret: ${JWT_SECRET}
