services:
  zookeeper:
    image: ubuntu/zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - prospectaai-network
  kafka:
    image: apache/kafka:3.8.0
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    ports:
      - "9092:9092"
    networks:
      - prospectaai-network
    healthcheck:
      test: ["CMD", "bash", "-c", "nc -z localhost 9092"]
      interval: 10s
      timeout: 5s
      retries: 10

  ms-auto-kafka-topic:
    build:
      context: .
      dockerfile: ./ms-auto-kafka-topic/Dockerfile
    container_name: ms-auto-kafka-topic
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "9000:9000"
    networks:
      - prospectaai-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10

  ms-useraccount:
    build:
      context: .
      dockerfile: ./ms-useraccount/Dockerfile
    container_name: ms-useraccount
    depends_on:
      ms-auto-kafka-topic:
        condition: service_completed_successfully
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      GOOGLE_CLIENT_ID: ${ENV_GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${ENV_GOOGLE_CLIENT_SECRET} 
      GITHUB_CLIENT_ID: ${ENV_GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${ENV_GITHUB_CLIENT_SECRET}
      JWT_SECRET: ${ENV_JWT_SECRET}
      JWT_EXPIRATION-MS: ${ENV_JWT_EXPIRATION_MS} 
      JWT_REFRESH_EXPIRATION-MS: ${ENV_JWT_REFRESH_EXPIRATION}
    ports:
      - "8081:8081"
    networks:
      - prospectaai-network

  ms-billing-sbs:
    build:
      context: .
      dockerfile: ./ms-billing-sbs/Dockerfile
    container_name: ms-billing-sbs
    depends_on:
      ms-auto-kafka-topic:
        condition: service_completed_successfully
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8082:8082"
    networks:
      - prospectaai-network    

networks:
  prospectaai-network:
    driver: bridge