spring.application.name=ms-async-task
server.port=8084
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
eureka.instance.prefer-ip-address=true

serpapi.api-key=${SERPAPI_API_KEY:}
google.places.api-key=${GOOGLE_PLACES_API_KEY:}
serper.api-key=${SERPER_API_KEY:}

spring.datasource.url=jdbc:h2:mem:asyncdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

security.jwt.secret: ${JWT_SECRET}
security.jwt.expiration-ms: ${JWT_EXPIRATION-MS}
security.jwt.refresh-expiration-ms: ${JWT_REFRESH_EXPIRATION}
useraccount.service.base-url: ${USERACCOUNT_SERVICE_BASE_URL}
