current:
  year: 2025
ms:
  version: 1.0.0

server:
  port: 8081  
  forward-headers-strategy: framework

eureka:
  client:
    service-url.defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
  instance:
    prefer-ip-address: true

spring:
  application:
    name: ms-useraccount

  kafka: 
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer:  org.springframework.kafka.support.serializer.JsonSerializer
  
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: email, profile
            redirect-uri: "http://127.0.0.1:8080/api/v1/auth/login/oauth2/code/{registrationId}"
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope: read:user, user:email
            redirect-uri: "http://127.0.0.1:8080/api/v1/auth/login/oauth2/code/{registrationId}"

logging:
  level:
    org.springframework.security: INFO

security:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: ${JWT_EXPIRATION-MS}
    refresh-expiration-ms: ${JWT_REFRESH_EXPIRATION}

billing:
  service:
    base-url: ${BILLING_SERVICE_BASE_URL:http://ms-billing-sbs}

# URL base do frontend para redirects pós-OAuth2
frontend:
  base-url: ${FRONTEND_BASE_URL:http://localhost:4201}
