server.port=9000
spring.application.name=ms-auto-kafka-topic

# Actuator
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

# Kafka Config
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS}
# Criação automática de tópicos
spring.kafka.admin.auto-create=true
spring.kafka.admin.properties.bootstrap.servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS}